name: Tests
on:
  push:
  pull_request:
  schedule:
    - cron: 0 7 1 * *
jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        python-version:
          - 3.5
          - 3.6
          - 3.7
          - 3.8
          - 3.9
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install non-Python dependencies
        run: >
          sudo apt -qy install
          pkg-config
          libsmi2-dev
          libsnmp-dev
          snmp-mibs-downloader
          ncurses-term
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions wheel
      - name: Run tests with tox
        run: tox
      - name: Collect coveralls data
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel: true

  coveralls_finish:
    name: Coveralls.io
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Send results to coveralls.io
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel-finished: true
